name: nirogi
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.0
  image_picker:
  rflutter_alert: ^1.0.2
  shared_preferences:
  flutter_bloc:
  image_cropper: ^1.0.2
  flutter_image_compress: ^0.6.1
  meta:
  equatable:
  bloc:
  flutter_fluid_slider: ^1.0.1
  http:
  flare_flutter: 1.0.2
  flutter_spinkit: "^3.1.0"
  webview_flutter: ^0.3.9+1
  flutter_html:
  carousel_slider: ^1.3.0
  flutter_swiper:
  intl: ^0.15.8
  dio:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
   - assets/images/logos/
   - assets/images/icons/
   - assets/images/province/
   - assets/gifs/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Bold.ttf
        - asset: assets/fonts/Karla-BoldItalic.ttf
        - asset: assets/fonts/Karla-Italic.ttf
        - asset: assets/fonts/Karla-Regular.ttf
    - family: Alex
      fonts:
        - asset: assets/fonts/DancingScript-Regular.otf